############################################################################
# boards/hazk03-stm32f105rb/src/Makefile
#
# SPDX-License-Identifier: Apache-2.0
#
############################################################################

include $(TOPDIR)/Make.defs

CSRCS  = stm32_boot.c stm32_bringup.c stm32_clockconfig.c
CSRCS += stm32_display.c tm1629a.c sm1626d.c ds3231.c

include $(TOPDIR)/boards/Board.mk
